services:
  app:
    image: my-rest-project-img
    ports:
      - "8080:8080"
    env_file:
      ".env"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/my_project_db
      - SPRING_DATA_REDIS_HOST=host.docker.internal
